#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to cleanup all ongoing sample productions.
#
# v1.0                                                                         C.Paus (May 03, 2017)
# --------------------------------------------------------------------------------------------------
# environment has to be setup: Kraken agents
source XX-KRAKEN_AGENTS_BASE-XX/setup.sh
source $KRAKEN_BASE/agents/cycle.cfg
# it is unclear to me why this does not get properly loaded in the line before
export PATH=${PATH}:${KRAKEN_BASE}/bin:${FIBS_BASE}/bin:${T2TOOLS_BASE}/bin
export PYTHONPATH=${PYTHONPATH}:${KRAKEN_BASE}/python:${FIBS_BASE}/python:${T2TOOLS_BASE}/python

# daemon
daemon=`basename $0`

# go to work area
cd $KRAKEN_AGENTS_WORK
echo ""
echo " Work area: "`pwd`
echo ""

# infinite loop
while [ 1 ]
do

  # make sure the log/web directories exists
  mkdir -p $KRAKEN_AGENTS_LOG/${daemon}
  mkdir -p $KRAKEN_AGENTS_WWW

  if [ -e "$KRAKEN_AGENTS_LOG/${daemon}" ] && [ -e "$KRAKEN_AGENTS_WWW" ]
  then
    #echo " Request review log/web areas exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " reviewd: Log/web area not found ($KRAKEN_AGENTS_LOG/${daemon},$KRAKEN_AGENTS_WWW)."
    echo " EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file (to be used once logfile detaches)
  tag=`date "+%s"`
  logFile=$KRAKEN_AGENTS_LOG/${daemon}/${daemon}.log
  rm -f $logFile
  touch $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L  M I T _ P R O D   E N V I R O N M E N T  = = = =" >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^KRAKEN | sort                                                       >> $logFile
  echo ""                                                                          >> $logFile
  echo " = = = =  I N I T I A L   C L E A N U P   E N V I R O N M E N T  = = = ="  >> $logFile
  echo ""                                                                          >> $logFile
  env  | grep ^KRAKEN_CLEANUP | sort                                               >> $logFile
  echo ""                                                                          >> $logFile
  echo "[ PYTHON PATH: $PYTHONPATH ]"                                              >> $logFile
  echo ""                                                                          >> $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9`
  do
    # period 3600 * nHours
    wait=$KRAKEN_CLEANUP_CYCLE_SECONDS
    echo " "                                                                      >> $logFile
    echo " request review loop $index started -- $tag (cycle wait $wait sec)"     >> $logFile
    echo " "                                                                      >> $logFile
    echo "   --> "`date`                                                          >> $logFile
    echo " "                                                                      >> $logFile

    # load updated config
    source $KRAKEN_BASE/agents/cycle.cfg
    echo " = = = =  U P D A T E D  C L E A N U P  E N V I R O N M E N T  = = = =" >> $logFile
    echo ""                                                                       >> $logFile
    env |grep ^KRAKEN_CLEANUP | sort                                              >> $logFile
    echo ""                                                                       >> $logFile

    # loop over all requested configurations
    for reqset in $KRAKEN_CLEANUP_CYCLE
    do

      echo " ==== Request Set: $reqset"                                           >> $logFile

      cfg=`echo $reqset | cut -d: -f1`
      vrs=`echo $reqset | cut -d: -f2`
      pys=`echo $reqset | cut -d: -f3`

      for py in `echo $pys | tr ',' ' '`
      do

        echo " ====-- cfg: $cfg, vrs: $vrs, py: $py"                              >> $logFile
        echo " "                                                                  >> $logFile

        # Make relevant directories
        #==========================

        mkdir -p $KRAKEN_AGENTS_LOG/reviewd/${cfg}/${vrs}   # not very consistent but historical

        # Full cleanup cycle
        #===================
        
        stdbuf -o0 -e0 reviewRequests.py --config=$cfg --version=$vrs --py=$py \
                         $KRAKEN_CLEANUP_OPTIONS                                  >> $logFile 2>&1
        echo " "                                                                  >> $logFile

        # keep log file up to speed
        synchronizeWeb.py                                                         >> $logFile

      done

    done

    echo " completed cleanup cycle."                                              >> $logFile
    echo " FINISH by updating log files on web."                                  >> $logFile

    sleep $wait
  done

  # move completed log file to a dated version before starting over
  mv $logFile $KRAKEN_AGENTS_LOG/${daemon}/${daemon}-${tag}.log

done

exit 0;
